### ISSUE TITLE
File names with spaces

### ISSUE THREAD

**Issue by qwert2003** [simon-rechermann/py_pdf2rmnotebook#1]
The program does not handle yet pdf file names with spaces.

At least on Linux the program fails for the file name "Flyer Sportkurse.pdf":
`~/extract/py_pdf2rmnotebook> python3.11 pdf2rmnotebook.py bsp/Flyer\ Sportkurse.pdf`

**Comment by simon-rechermann** [comment]
Is this fix sufficient for you? I just remove spaces from the file name. So the rmdoc file and the notebook will be called "FlyerSportkurse"
